spring:
  config:
    import: "classpath:/config/application-default.yml"
    use-legacy-processing: true
    activate:
      on-profile: local
    jpa:
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          use_sql_comments: true

  datasource:
    master:
      hikari:
        pool-name: "demoApp-master"
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://localhost:3306"
        username: root
        password: root
        maximum-pool-size: 50
        read-only: false

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
      retry:
        max-attempts: 2   # 최대 재시도 횟수
      pool:
        netty-threads: 10  # Netty 스레드 풀 크기

  kafka:
    bootstrap-servers: localhost:9092
