spring:
  config:
    import: "classpath:/config/application-default.yml"
    use-legacy-processing: true
    activate:
      on-profile: dev
    jpa:
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          use_sql_comments: true

  # MSSQL DB & Hikari DBCP 설정
  datasource:
    master:
      hikari:
        pool-name: "tlmApp-master"
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: "jdbc:sqlserver://10.125.111.134:1433;databaseName=EP_BE_TLM_ADMIN;encrypt=false;sendStringParametersAsUnicode=false"
        username: ENC(uT42xBcJ4NlyQG2cflBnIg==)
        password: ENC(VCTnWiQRLP6keok5zek4kCUvJoSuVQ6K)
        maximum-pool-size: 50
        read-only: false

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
      retry:
        max-attempts: 2   # 최대 재시도 횟수
      pool:
        netty-threads: 10  # Netty 스레드 풀 크기

  # Kafka Bootstrap
  kafka:
    bootstrap-servers: localhost:9092
